from typing import Callable, Optional

from .util import *



def _vertex_uv_channel_count(vertices: List[Vertex]) -> int:
    if not vertices:
        return 0
    n = len(vertices[0].uvs)
    for i, v in enumerate(vertices):
        if len(v.uvs) != n:
            raise ValueError(
                f"顶点 {i} 的 UV 层数 {len(v.uvs)} 与首顶点 {n} 不一致"
            )
    return n


    
def write_vertices_to_obj(
    vertices: List[Vertex],
    indices: List[int],
    filepath: str,
    *,
    uv_channel_index: int = 0,
    flip_normals: bool = True,
    flip_winding: bool = True,
    config: Optional[ExportConfig] = None,
    on_progress: Optional[Callable[[int, int], None]] = None,
) -> None:
    """
    将顶点列表与紧凑三角形索引写入 Wavefront OBJ（UTF-8）。
    每个顶点槽写 v、vn；若存在 UV 则写一行 vt（使用 uvs[uv_channel_index] 的 x,y）。
    f：有 vt 时为 i/i/i；无 vt 时为 i//i（仅位置+法线）。
    末尾不足 3 个的索引会被忽略。

    flip_normals：对法线取反（常见 D3D/裁剪空间与 OBJ 右手系不一致）。
    flip_winding：每个三角形交换第二、第三个角点，反转绕序（与 flip_normals 一起修正背面剔除与光照）。
    config：若提供则使用其中的 up_axis、flip_normals、flip_winding；未提供时 flip_* 用参数默认值。
    on_progress：可选 (current, total)，在写入顶点与面时周期性回调，便于 UI 进度条。
    """
    if config is not None:
        flip_normals = config.flip_normals
        flip_winding = config.flip_winding
    if not vertices:
        raise ValueError("vertices 为空")
    for i in indices:
        if i < 0 or i >= len(vertices):
            raise IndexError(f"索引 {i} 超出顶点范围 0..{len(vertices) - 1}")

    n_uv = _vertex_uv_channel_count(vertices)
    if n_uv > 0 and (uv_channel_index < 0 or uv_channel_index >= n_uv):
        raise IndexError(f"uv_channel_index={uv_channel_index} 超出 0..{n_uv - 1}")

    def _pose(x: float, y: float, z: float) -> tuple:
        if config is None:
            return (x, y, z)
        return config.transform_xyz(x, y, z)

    up_note = f"up_axis={config.up_axis}" if config else "up_axis=Z (default)"
    lines: List[str] = [
        "# generated by write_vertices_to_obj",
        f"# uv_channel_index={uv_channel_index}" if n_uv else "# no uv",
        f"# flip_normals={flip_normals} flip_winding={flip_winding} {up_note}",
        "",
    ]
    tri_len = len(indices) - len(indices) % 3
    tri_count = tri_len // 3
    total_steps = len(vertices) + tri_count
    if total_steps < 1:
        total_steps = 1
    prog_stride = max(1, total_steps // 150)
    prog_step = 0

    for v in vertices:
        px, py, pz = _pose(v.Position.x, v.Position.y, v.Position.z)
        lines.append(f"v {px} {py} {pz}")
        if v.Normal is None:
            nx, ny, nz = _pose(0.0, 0.0, 1.0)
            lines.append(f"vn {nx} {ny} {nz}")
        else:
            nx, ny, nz = _pose(v.Normal.x, v.Normal.y, v.Normal.z)
            if flip_normals:
                lines.append(f"vn {-nx} {-ny} {-nz}")
            else:
                lines.append(f"vn {nx} {ny} {nz}")
        if n_uv:
            uv = v.uvs[uv_channel_index]
            lines.append(f"vt {uv.x} {uv.y}")
        prog_step += 1
        if on_progress is not None and (
            prog_step % prog_stride == 0 or prog_step == len(vertices)
        ):
            on_progress(prog_step, total_steps)

    lines.append("")
    for t in range(0, tri_len, 3):
        a = indices[t] + 1
        b = indices[t + 1] + 1
        c = indices[t + 2] + 1
        if flip_winding:
            b, c = c, b
        if n_uv:
            lines.append(f"f {a}/{a}/{a} {b}/{b}/{b} {c}/{c}/{c}")
        else:
            lines.append(f"f {a}//{a} {b}//{b} {c}//{c}")
        prog_step += 1
        if on_progress is not None and (
            prog_step % prog_stride == 0 or prog_step == total_steps
        ):
            on_progress(prog_step, total_steps)

    if on_progress is not None:
        on_progress(total_steps, total_steps)

    with open(filepath, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")


def write_vertices_to_obj_per_uv(
    vertices: List[Vertex],
    indices: List[int],
    filepath: str,
    *,
    flip_normals: bool = True,
    flip_winding: bool = True,
    config: Optional[ExportConfig] = None,
    on_progress: Optional[Callable[[int, int], None]] = None,
) -> List[str]:
    """
    根据 UV 层数写出 OBJ 路径列表。
    - 0 套 UV：写单个 filepath，面为 v//vn。
    - 1 套 UV：写单个 filepath，面为 v/vt/vn。
    - 多于 1 套 UV：为每一套写 stem_uv0.obj、stem_uv1.obj…（不覆盖 filepath 本身）。
    on_progress：可选 (current, total)，跨多个 OBJ 文件汇总进度。
    """
    if not vertices:
        raise ValueError("vertices 为空")
    n_uv = len(vertices[0].uvs)
    nv = len(vertices)
    tri_count = (len(indices) - len(indices) % 3) // 3
    per_file = nv + tri_count
    if per_file < 1:
        per_file = 1
    num_files = 1 if n_uv <= 1 else n_uv
    overall = max(1, per_file * num_files)

    def wrap_cb(file_index: int):
        if on_progress is None:
            return None
        base = file_index * per_file

        def cb(cur: int, tot: int) -> None:
            on_progress(base + cur, overall)

        return cb

    if filepath.lower().endswith(".obj"):
        stem = filepath[:-4]
        ext = ".obj"
    else:
        stem = filepath
        ext = ".obj"

    written: List[str] = []
    if n_uv <= 1:
        out = filepath if filepath.lower().endswith(".obj") else filepath + ext
        write_vertices_to_obj(
            vertices,
            indices,
            out,
            uv_channel_index=0,
            flip_normals=flip_normals,
            flip_winding=flip_winding,
            config=config,
            on_progress=wrap_cb(0),
        )
        written.append(out)
        return written

    for ch in range(n_uv):
        out = f"{stem}_uv{ch}{ext}"
        write_vertices_to_obj(
            vertices,
            indices,
            out,
            uv_channel_index=ch,
            flip_normals=flip_normals,
            flip_winding=flip_winding,
            config=config,
            on_progress=wrap_cb(ch),
        )
        written.append(out)
    return written
